//! Global user-interface typography for RustMix Wave.
//!
//! UI text uses pre-rasterized 1-bpp glyph atlases of Inter (Medium for
//! body text, SemiBold for headings), generated by
//! `tools/fontgen/gen_bitmap_fonts.py` like the Reader's book strikes.

use embedded_graphics::{
    pixelcolor::BinaryColor,
    prelude::{DrawTarget, Pixel, Point},
};

use super::display::{DisplayPreferences, UiFontSize};

mod assets;

#[cfg(test)]
pub mod audit {
    use std::cell::RefCell;

    use embedded_graphics::prelude::Point;

    use super::{TextBounds, UiTextStyle};

    #[derive(Clone, Debug)]
    pub struct Rec {
        pub text: String,
        pub x: i32,
        pub baseline: i32,
        pub width: i32,
        pub ink_top: i32,
        pub ink_bottom: i32,
        pub clip: Option<(i32, i32, i32, i32)>,
    }

    thread_local! {
        static RECORDS: RefCell<Option<Vec<Rec>>> = const { RefCell::new(None) };
    }

    pub fn start() {
        RECORDS.with(|records| *records.borrow_mut() = Some(Vec::new()));
    }

    pub fn take() -> Vec<Rec> {
        RECORDS.with(|records| records.borrow_mut().take().unwrap_or_default())
    }

    pub fn record(text: &str, baseline: Point, style: UiTextStyle, bounds: Option<TextBounds>) {
        RECORDS.with(|records| {
            if let Some(list) = records.borrow_mut().as_mut() {
                for (index, line) in text.split('\n').enumerate() {
                    let (top, bottom) = style.text_ink_bounds(line);
                    let y = baseline.y + index as i32 * i32::from(style.line_height());
                    list.push(Rec {
                        text: line.to_string(),
                        x: baseline.x,
                        baseline: y,
                        width: style.text_width(line),
                        ink_top: y + top,
                        ink_bottom: y + bottom,
                        clip: bounds.map(|b| (b.left, b.top, b.right, b.bottom)),
                    });
                }
            }
        });
    }
}

/// One rasterized glyph: its ink box relative to the pen position on the
/// text baseline, and how far the pen then advances.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Glyph {
    pub offset: u32,
    pub width: u8,
    pub height: u8,
    pub advance: u8,
    pub left: i8,
    pub top: i8,
}

/// Compact constructor the generated strike tables are written with.
#[must_use]
pub const fn g(offset: u32, width: u8, height: u8, advance: u8, left: i8, top: i8) -> Glyph {
    Glyph {
        offset,
        width,
        height,
        advance,
        left,
        top,
    }
}

/// One bitmap-font strike: printable ASCII indexed by code point, plus the
/// extra glyphs (Latin-1 and the Windows-1252 typographic characters)
/// sorted by `char` for a binary search.
#[derive(Clone, Copy, Debug)]
pub struct BitmapFont {
    pub glyphs: &'static [Glyph; 95],
    pub bitmap: &'static [u8],
    pub extra: &'static [(char, Glyph)],
    pub line_height: u8,
}

impl BitmapFont {
    #[must_use]
    fn glyph(self, character: char) -> Glyph {
        let code = character as u32;
        if (32..=126).contains(&code) {
            return self.glyphs[(code - 32) as usize];
        }
        if let Ok(index) = self
            .extra
            .binary_search_by_key(&character, |(candidate, _)| *candidate)
        {
            return self.extra[index].1;
        }
        // No glyph: other spaces advance like a space, anything else is `?`.
        let fallback = if character.is_whitespace() { ' ' } else { '?' };
        self.glyphs[(fallback as usize) - 32]
    }
}

/// Semantic UI text role. A size profile selects the concrete raster strike.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UiTextRole {
    /// Labels, descriptions, secondary lines, hints and footers: the
    /// smallest text the interface draws. There used to be a `Detail` role
    /// one size under it (11 to 13 px); on the panel it was too small to
    /// read, and nothing uses a size below this one any more.
    Body,
    /// Menu titles, section headings and selected-row emphasis.
    Heading,
    /// Product titles and large sensor values.
    Large,
}

/// Half-open clipping rectangle for bounded text drawing.
///
/// Reader pages use this guard so body glyphs cannot cross the shared body
/// viewport even when a proportional bitmap strike contains a wide glyph.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TextBounds {
    pub left: i32,
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
}

impl TextBounds {
    #[must_use]
    pub const fn new(left: i32, top: i32, right: i32, bottom: i32) -> Self {
        Self {
            left,
            top,
            right,
            bottom,
        }
    }

    #[must_use]
    pub const fn width(self) -> i32 {
        self.right - self.left
    }

    #[must_use]
    const fn contains(self, point: Point) -> bool {
        point.x >= self.left && point.x < self.right && point.y >= self.top && point.y < self.bottom
    }
}

/// Transparent UI text style used by the firmware-local bitmap renderer.
#[derive(Clone, Copy, Debug)]
pub struct UiTextStyle {
    font: &'static BitmapFont,
    color: BinaryColor,
}

impl UiTextStyle {
    #[must_use]
    pub const fn new(font: &'static BitmapFont, color: BinaryColor) -> Self {
        Self { font, color }
    }

    /// Same strike, a different ink color — used to invert a line of text
    /// (e.g. white-on-black) without needing the caller to know the
    /// underlying font.
    #[must_use]
    pub const fn with_color(self, color: BinaryColor) -> Self {
        Self { color, ..self }
    }

    #[must_use]
    pub const fn line_height(self) -> u8 {
        self.font.line_height
    }

    /// Measure one line using this bitmap strike. Characters without a
    /// glyph follow the same fallback as drawing.
    #[must_use]
    pub fn text_width(self, text: &str) -> i32 {
        text.chars()
            .filter(|character| *character != '\n')
            .map(|character| i32::from(self.font.glyph(character).advance))
            .sum()
    }

    /// Vertical extent of one line's actual ink, as `(top, bottom)` offsets
    /// from the text baseline (top is negative — glyphs sit above their
    /// baseline). Unlike [`Self::line_height`], which is the font's full
    /// line pitch (ascent + descent + leading, sized to fit any glyph
    /// including descenders no particular string uses), this reflects only
    /// the glyphs actually present — e.g. an all-digits label with no
    /// descenders reports a shorter, higher box. Callers that need to center
    /// a short label's *visible* ink inside a tightly-fitted shape (a badge
    /// pill, not a text-flow line) should measure with this, not
    /// `line_height`, or the centering will read as pushed toward the top.
    #[must_use]
    pub fn text_ink_bounds(self, text: &str) -> (i32, i32) {
        let mut top = 0;
        let mut bottom = 0;
        let mut any = false;
        for character in text.chars().filter(|character| *character != '\n') {
            let glyph = self.font.glyph(character);
            if glyph.width == 0 || glyph.height == 0 {
                continue;
            }
            let glyph_top = i32::from(glyph.top);
            let glyph_bottom = glyph_top + i32::from(glyph.height);
            if !any {
                top = glyph_top;
                bottom = glyph_bottom;
                any = true;
            } else {
                top = top.min(glyph_top);
                bottom = bottom.max(glyph_bottom);
            }
        }
        (top, bottom)
    }
}

/// Small drop-in drawable mirroring the `Text::new(...).draw(...)` call shape
/// used by the existing shell screens.
pub struct Text<'a> {
    text: &'a str,
    baseline: Point,
    style: UiTextStyle,
}

impl<'a> Text<'a> {
    #[must_use]
    pub const fn new(text: &'a str, baseline: Point, style: UiTextStyle) -> Self {
        Self {
            text,
            baseline,
            style,
        }
    }

    /// Draw transparent text and return the cursor position after the final
    /// glyph. Characters the strike has no glyph for are drawn as `?`.
    pub fn draw<D>(&self, display: &mut D) -> Result<Point, D::Error>
    where
        D: DrawTarget<Color = BinaryColor>,
    {
        self.draw_with_bounds(display, None)
    }

    /// Draw transparent text while discarding pixels outside one half-open
    /// viewport. The returned cursor still advances through the full string so
    /// callers can use this as a final rendering guard without altering source
    /// byte anchors or pagination state.
    pub fn draw_clipped<D>(&self, display: &mut D, bounds: TextBounds) -> Result<Point, D::Error>
    where
        D: DrawTarget<Color = BinaryColor>,
    {
        self.draw_with_bounds(display, Some(bounds))
    }

    fn draw_with_bounds<D>(
        &self,
        display: &mut D,
        bounds: Option<TextBounds>,
    ) -> Result<Point, D::Error>
    where
        D: DrawTarget<Color = BinaryColor>,
    {
        #[cfg(test)]
        audit::record(self.text, self.baseline, self.style, bounds);
        let start_x = self.baseline.x;
        let mut cursor = self.baseline;
        for character in self.text.chars() {
            if character == '\n' {
                cursor.x = start_x;
                cursor.y += i32::from(self.style.font.line_height);
                continue;
            }
            let glyph = self.style.font.glyph(character);
            draw_glyph(display, cursor, glyph, self.style, bounds)?;
            cursor.x += i32::from(glyph.advance);
        }
        Ok(cursor)
    }
}

fn draw_glyph<D>(
    display: &mut D,
    baseline: Point,
    glyph: Glyph,
    style: UiTextStyle,
    bounds: Option<TextBounds>,
) -> Result<(), D::Error>
where
    D: DrawTarget<Color = BinaryColor>,
{
    let width = usize::from(glyph.width);
    let stride = width.div_ceil(8);
    let offset = glyph.offset as usize;
    let origin_x = baseline.x + i32::from(glyph.left);
    let origin_y = baseline.y + i32::from(glyph.top);
    // One `draw_iter` call per glyph (not per ink pixel), so the target's
    // per-call setup -- e.g. `OrientedFrameBuffer`'s orientation dispatch --
    // runs once per glyph.
    let ink = (0..usize::from(glyph.height)).flat_map(move |row| {
        let row_bits = &style.font.bitmap[offset + row * stride..offset + (row + 1) * stride];
        (0..width).filter_map(move |column| {
            if row_bits[column / 8] & (0x80 >> (column % 8)) == 0 {
                return None;
            }
            let point = Point::new(origin_x + column as i32, origin_y + row as i32);
            bounds
                .map_or(true, |clip| clip.contains(point))
                .then_some(Pixel(point, style.color))
        })
    });
    display.draw_iter(ink)
}

/// Resolve a firmware-local bitmap strike for one size profile and role.
#[must_use]
pub const fn style_for(size: UiFontSize, role: UiTextRole, color: BinaryColor) -> UiTextStyle {
    use assets::*;
    use UiFontSize::{Compact, Large, Standard};
    use UiTextRole::{Body, Heading, Large as LargeRole};

    let font = match (size, role) {
        (Compact, Body) => &INTER_COMPACT_BODY,
        (Compact, Heading) => &INTER_COMPACT_HEADING,
        (Compact, LargeRole) => &INTER_COMPACT_LARGE,
        (Standard, Body) => &INTER_STANDARD_BODY,
        (Standard, Heading) => &INTER_STANDARD_HEADING,
        (Standard, LargeRole) => &INTER_STANDARD_LARGE,
        (Large, Body) => &INTER_LARGE_BODY,
        (Large, Heading) => &INTER_LARGE_HEADING,
        (Large, LargeRole) => &INTER_LARGE_LARGE,
    };
    UiTextStyle::new(font, color)
}

impl DisplayPreferences {
    #[must_use]
    pub const fn text_style(self, role: UiTextRole, color: BinaryColor) -> UiTextStyle {
        style_for(self.font_size, role, color)
    }

    #[must_use]
    pub const fn body_style(self) -> UiTextStyle {
        self.text_style(UiTextRole::Body, BinaryColor::On)
    }

    #[must_use]
    pub const fn heading_style(self) -> UiTextStyle {
        self.text_style(UiTextRole::Heading, BinaryColor::On)
    }

    #[must_use]
    pub const fn large_style(self) -> UiTextStyle {
        self.text_style(UiTextRole::Large, BinaryColor::On)
    }

    #[must_use]
    pub const fn header_title_style(self) -> UiTextStyle {
        self.text_style(UiTextRole::Large, BinaryColor::On)
    }

    #[must_use]
    pub const fn navigation_style(self) -> UiTextStyle {
        self.heading_style()
    }

    #[must_use]
    pub const fn footer_style(self) -> UiTextStyle {
        self.body_style()
    }
}

#[cfg(test)]
mod tests {
    use embedded_graphics::{mock_display::MockDisplay, pixelcolor::BinaryColor, prelude::Point};

    use super::{style_for, BitmapFont, Text, TextBounds, UiTextRole};
    use crate::{
        app::{
            display::{DisplayPreferences, UiFontSize},
            reader_typography::reader_body_style,
        },
        reader::{BookFont, BookFontSize, ReadingTheme},
    };

    /// Every strike the firmware can select, UI and Reader alike.
    fn all_strikes() -> Vec<&'static BitmapFont> {
        let mut strikes = Vec::new();
        for size in [UiFontSize::Compact, UiFontSize::Standard, UiFontSize::Large] {
            for role in [UiTextRole::Body, UiTextRole::Heading, UiTextRole::Large] {
                strikes.push(style_for(size, role, BinaryColor::On).font);
            }
        }
        for family in [BookFont::Literata, BookFont::AtkinsonHyperlegible] {
            for size in [
                BookFontSize::Large,
                BookFontSize::XLarge,
                BookFontSize::XXLarge,
                BookFontSize::XXXLarge,
            ] {
                strikes.push(reader_body_style(family, size, ReadingTheme::Classic).font);
            }
        }
        strikes
    }

    #[test]
    fn renders_inter_standard_ascii_text() {
        let mut display = MockDisplay::<BinaryColor>::new();
        display.set_allow_overdraw(true);
        let style = DisplayPreferences::default().body_style();
        // Keep the representative ASCII sample inside MockDisplay's
        // default 64 × 64 surface after the v0.13.2 readability scaling.
        let cursor = Text::new("RustMix", Point::new(0, 24), style)
            .draw(&mut display)
            .unwrap();
        assert!(cursor.x > 0);
    }

    #[test]
    fn clipped_text_guard_discards_pixels_outside_bounds() {
        let mut display = MockDisplay::<BinaryColor>::new();
        display.set_allow_overdraw(true);
        let style = DisplayPreferences::default().body_style();
        let cursor = Text::new("RustMix", Point::new(0, 24), style)
            .draw_clipped(&mut display, TextBounds::new(0, 0, 10, 64))
            .unwrap();
        assert!(cursor.x > 10);
    }

    #[test]
    fn every_strike_has_sorted_accent_and_typography_glyphs() {
        for font in all_strikes() {
            assert!(font.extra.windows(2).all(|pair| pair[0].0 < pair[1].0));
            // Italian, French, German letters and the curly apostrophe,
            // guillemets, dashes, ellipsis and euro that books use.
            for character in "àèéìòùÀÈÉÌÒÙçÇñüößœ’‘“”«»–—…€".chars()
            {
                let glyph = font.glyph(character);
                assert_ne!(glyph, font.glyph('?'), "missing {character}");
            }
        }
    }

    /// The percent sign is two rings joined by a slash, so every row of
    /// its ink box has ink. The 12 px strike once came out of the rasterizer
    /// as two smudges with blank rows between them, unreadable as "%" on
    /// the battery and progress labels.
    #[test]
    fn the_percent_sign_is_whole_in_every_strike() {
        for font in all_strikes() {
            let glyph = font.glyph('%');
            let stride = usize::from(glyph.width).div_ceil(8);
            for row in 0..usize::from(glyph.height) {
                let start = glyph.offset as usize + row * stride;
                assert!(
                    font.bitmap[start..start + stride]
                        .iter()
                        .any(|byte| *byte != 0),
                    "blank row {row} in a {}-px-line strike",
                    font.line_height
                );
            }
        }
    }

    #[test]
    fn missing_glyphs_fall_back_to_space_or_question_mark() {
        let style = DisplayPreferences::default().body_style();
        // Thin space: no glyph of its own, advances like a space.
        assert_eq!(style.text_width("\u{2009}"), style.text_width(" "));
        // Cyrillic: no glyph, drawn as '?'.
        assert_eq!(style.text_width("Ж"), style.text_width("?"));
    }

    #[test]
    fn no_interface_text_is_smaller_than_the_body_size() {
        // Body is the smallest role, in every size the user can choose; the
        // 11 to 13 px strikes that sat under it were unreadable on the panel.
        for (size, body_line) in [
            (UiFontSize::Compact, 18),
            (UiFontSize::Standard, 20),
            (UiFontSize::Large, 23),
        ] {
            let line = |role| style_for(size, role, BinaryColor::On).line_height();
            assert_eq!(line(UiTextRole::Body), body_line, "{size:?}");
            assert!(
                line(UiTextRole::Heading) > line(UiTextRole::Body),
                "{size:?}"
            );
            assert!(
                line(UiTextRole::Large) > line(UiTextRole::Heading),
                "{size:?}"
            );
        }
    }

    #[test]
    fn standard_profile_is_readability_scaled() {
        let preferences = DisplayPreferences::default();
        assert!(preferences.body_style().line_height() >= 20);
        assert!(preferences.heading_style().line_height() >= 26);
    }

    #[test]
    fn resolves_large_profile() {
        let preferences = DisplayPreferences {
            font_size: UiFontSize::Large,
            ..DisplayPreferences::default()
        };
        assert!(
            preferences.heading_style().line_height() >= preferences.body_style().line_height()
        );
    }
}
