//! Reader-specific body typography.
//!
//! Reader pages deliberately use an independent font preference boundary so
//! global UI typography remains stable. Literata Medium and Atkinson
//! Hyperlegible Next Medium use Reader-only bitmap strikes generated by
//! `tools/fontgen/gen_bitmap_fonts.py`; text normalization folds the few
//! characters they have no glyph for before layout.

use embedded_graphics::pixelcolor::BinaryColor;

use super::{
    reader_atkinson_next_assets::{
        ATKINSON_NEXT_LARGE, ATKINSON_NEXT_XLARGE, ATKINSON_NEXT_XXLARGE, ATKINSON_NEXT_XXXLARGE,
    },
    reader_literata_assets::{
        LITERATA_LARGE, LITERATA_XLARGE, LITERATA_XXLARGE, LITERATA_XXXLARGE,
    },
    typography::{BitmapFont, UiTextStyle},
};
use crate::reader::{BookFont, BookFontSize, ReadingTheme};

/// Resolve one Reader body strike without affecting global UI preferences.
#[must_use]
pub const fn reader_body_style(
    family: BookFont,
    size: BookFontSize,
    _theme: ReadingTheme,
) -> UiTextStyle {
    let font = match family {
        BookFont::Literata => literata_font(size),
        BookFont::AtkinsonHyperlegible => atkinson_next_font(size),
    };
    UiTextStyle::new(font, BinaryColor::On)
}

#[must_use]
const fn atkinson_next_font(size: BookFontSize) -> &'static BitmapFont {
    match size {
        BookFontSize::Large => &ATKINSON_NEXT_LARGE,
        BookFontSize::XLarge => &ATKINSON_NEXT_XLARGE,
        BookFontSize::XXLarge => &ATKINSON_NEXT_XXLARGE,
        BookFontSize::XXXLarge => &ATKINSON_NEXT_XXXLARGE,
    }
}

#[must_use]
const fn literata_font(size: BookFontSize) -> &'static BitmapFont {
    match size {
        BookFontSize::Large => &LITERATA_LARGE,
        BookFontSize::XLarge => &LITERATA_XLARGE,
        BookFontSize::XXLarge => &LITERATA_XXLARGE,
        BookFontSize::XXXLarge => &LITERATA_XXXLARGE,
    }
}

#[cfg(test)]
mod tests {
    use super::reader_body_style;
    use crate::reader::{BookFont, BookFontSize, ReadingTheme};

    #[test]
    fn resolves_all_reader_body_profiles() {
        for family in [BookFont::Literata, BookFont::AtkinsonHyperlegible] {
            let mut previous = 0;
            for size in [
                BookFontSize::Large,
                BookFontSize::XLarge,
                BookFontSize::XXLarge,
                BookFontSize::XXXLarge,
            ] {
                let line_height =
                    reader_body_style(family, size, ReadingTheme::Classic).line_height();
                assert!(line_height > previous);
                previous = line_height;
            }
        }
    }
}
